FROM node:alpine as builder
WORKDIR /app

# copy the json file first
COPY ./package.json /app

# install npm dependencies
RUN yarn install

# copy other project files
COPY . .

# build the folder
CMD [ "npm", "run", "dev" ]