version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
